name: flutter_messaging_chatwoot
description: A new Flutter package project.
version: 0.0.1-alpha
homepage:

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_messaging_base: 
    git: 'https://github.com/phr34k/flutter_messaging_base.git'
  provider: any
  flutter_chat_ui: ^1.5.5
  uuid: any
  file_picker: any
  image_picker: any
  mime: any
  open_file: any
  rxdart: any
  hive: any
  hive_flutter: any
  badges: any

  json_annotation: ^4.0.1
  dio: ^4.0.0
  web_socket_channel: ^2.1.0  
  equatable: ^2.0.3  
  riverpod: ^0.14.0+3
  synchronized: ^3.0.0
  stream_channel: ^2.1.0
  intl: ^0.17.0  
  async: ^2.5.0

dependency_overrides:
#  flutter_messaging_base:
#  path: ../flutter_messaging_base      

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.0.7
  json_serializable: ^6.1.5
  hive_generator: any
  build_runner: any

flutter:
